### ISSUE TITLE
Form - Resource name field

### ISSUE THREAD

**Issue by simrandhaliw** [patternfly/AI-infra-ui-components#4]
**Is this a new component or an extension of an existing one?**
We already use the 'Resource name' link button in some areas of the UI (e.g., in the project creation modal). However, we want to change how this button is presented and develop a consistent pattern that can be applied wherever it is relevant.

**Describe the feature**
- This is a button to help users to view or edit the resource name of an object in a creation form.
- The resource name will capture the name to generate a value by default and the resource name will be displayed in the help text under the ‘Name’ field. 
- If users need to edit the resource name by themselves, they can click the ‘Edit resource name’ button to edit it. 
- The resource name is not editable after the creation.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
[Here](https://docs.google.com/document/d/1hiIf4bE06cUcI5xU9-n6i3vt6h_dVP4haI0b2gf-qac/edit#heading=h.b35ifc4bfibk) is the link to the guideline document that describes this pattern and provides examples.

**Any other information?**
For any UX queries regarding this pattern, please contact Kun (Xiankun Li) and Sim Dhaliwal.

**Comment by adamviktora** [comment]
It looks like this component was already created in the odh-dashboard repository and is reusable. https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx

**Comment by adamviktora** [comment]
@simrandhaliw Would it be OK to add a "Description" text area field as part of this pattern?

The current component which is being used in RHOAI is `K8sNameDescriptionField` so the Description field is included. In the [pattern guidelines document](https://docs.google.com/document/d/1hiIf4bE06cUcI5xU9-n6i3vt6h_dVP4haI0b2gf-qac/edit), I see that the last screenshot (Model server) doesn't have the description field.

Is it ok to add a Description field? Or is the goal to have a component encapsulating only the Name and Resource name fields?
(also tagging @jeff-phillips-18)

**Comment by simrandhaliw** [comment]
This was discussed in Slack, and I'm sharing some notes from the thread here for transparency:
- [Jeff] The Form field is for entering the resource (display) name, giving the user the optional option of setting the actual resource name (k8s name field). The description field would be separate and I don’t think it needs to be included with the name field.
- [Jenn] These were designs that were recently handed over to the RHOAI eng team. These were implemented as part of [RHOAIENG-583](https://issues.redhat.com/browse/RHOAIENG-583). I think this pattern now falls into the category of existing UI components that we want to include for visibility and documentation. (Vs UI components that don’t exist where we want to provide guidance on how to implement)
